In [4]:
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [5]:
df = pd.read_csv("credit_worthiness_dataset.csv")
df.head(5)

Age  Income  Employment_Years  Education_Level  Credit_Score  Loan_Purpose  \
0   56  620600             12.04                3           809             1   
1   46  881756             23.36                3           729             3   
2   32  615484             10.55                1           406             1   
3   60  614302              5.56                3           740             3   
4   25  421426              5.57                3           783             1   

   Loan_Amount  Loan_Term_Days  Number_of_Open_Accounts  Outstanding Debt  \
0        16938             195                        4             12325   
1        17401             258                        4               724   
2        23207             278                       14             58324   
3        57457              70                       14             73812   
4        88261             359                        9             13406   

     DTI  Credit_Worthy  
0   1.99              1  
1   0.08              1  
2   9.48              0  
3  12.02              1  
4   3.18              1

In [6]:
df["Credit_Worthy"].value_counts()

1    2828
0    2172
Name: Credit_Worthy, dtype: int64

In [7]:
# Splitting the dataset into X and y. 
X = df.drop(columns=["Credit_Worthy"])
y = df["Credit_Worthy"]


In [8]:
# Split the data using train_test_split
# Assigned a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

In [9]:
# Created a StandardScaler instance.
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

SVM Model

In [10]:
# Initiated SVC classifier model instance
svm_model = svm.SVC()

# Fit the model to the data using the training data
svm_model = svm_model.fit(X_train_scaled, y_train)
 
# Used the testing data to make the model predictions
svm_pred = svm_model.predict(X_test_scaled)



In [11]:
# Accuracy score 
accuracy_score(y_test, svm_pred)

0.9888

In [12]:
# Generated a confusion matrix for the model

confusion_matrix(y_test, svm_pred)

array([[543,   4],
       [ 10, 693]])

In [13]:
# Generated a classification report for the model
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       547
           1       0.99      0.99      0.99       703

    accuracy                           0.99      1250
   macro avg       0.99      0.99      0.99      1250
weighted avg       0.99      0.99      0.99      1250



GB Model

In [14]:
# Initialized Gradient Boosting Classifier
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Fit the model
gb_clf.fit(X_train_scaled, y_train)

# Predicted the labels
gb_pred = gb_clf.predict(X_test_scaled)

In [15]:
# Accuracy score 
accuracy_score(y_test, gb_pred)

1.0

In [16]:
# Generated a confusion matrix for the model

confusion_matrix(y_test, gb_pred)

array([[547,   0],
       [  0, 703]])

In [17]:
# Generated a classification report for the model
print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       547
           1       1.00      1.00      1.00       703

    accuracy                           1.00      1250
   macro avg       1.00      1.00      1.00      1250
weighted avg       1.00      1.00      1.00      1250



Logistics Regression

In [18]:
# Initialized logistics Regression Classifier

lg_model = LogisticRegression(random_state=1)  

# Fit the model using training data
lg_model.fit(X_train_scaled,y_train)

LogisticRegression(random_state=1)

In [19]:
# Predicted the labels
lg_predictions = lg_model.predict(X_test_scaled)

In [20]:
# Accuracy score 
accuracy_score(y_test, lg_predictions)

0.992

In [21]:
# Generated a confusion matrix for the model
confusion_matrix(y_test, lg_predictions)

array([[543,   4],
       [  6, 697]])

In [22]:
# Generated a classification report for the model

print(classification_report(y_test, lg_predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       547
           1       0.99      0.99      0.99       703

    accuracy                           0.99      1250
   macro avg       0.99      0.99      0.99      1250
weighted avg       0.99      0.99      0.99      1250



Random Forest

In [23]:

# Initialized random forest Classifier

rf_model = RandomForestClassifier(random_state=1)

# Fit the model using training data
rf_model.fit(X_train_scaled,y_train)

RandomForestClassifier(random_state=1)

In [24]:
# Predicted the labels

rf_predictions = rf_model.predict(X_test_scaled)

In [25]:
# Accuracy score 

accuracy_score(y_test, rf_predictions)

1.0

In [26]:

# Generated a confusion matrix for the model

confusion_matrix(y_test, rf_predictions)

array([[547,   0],
       [  0, 703]])

In [27]:
# Generated a classification report for the model

print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       547
           1       1.00      1.00      1.00       703

    accuracy                           1.00      1250
   macro avg       1.00      1.00      1.00      1250
weighted avg       1.00      1.00      1.00      1250



Download Random Forest and Gradient Boosing Models


In [28]:
file_path = "random_forest_model.pkl"
joblib.dump(rf_model, file_path)

['random_forest_model.pkl']

In [29]:

file_path = "gb_model.pkl"
joblib.dump(gb_clf, file_path)

['gb_model.pkl']