In [125]:
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [126]:
df = pd.read_csv("credit_worthiness_dataset.csv")
df.head(5)

Age  Income  Employment_Years  Education_Level  Credit_Score  Loan_Purpose  \
0   56  620600             12.04                3           818             1   
1   46  881756             23.36                3           737             3   
2   32  615484             10.55                1           484             1   
3   60  614302              5.56                3           801             3   
4   25  421426              5.57                3           750             1   

   Loan_Amount  Loan_Term_Months  Number_of_Open_Accounts  Outstanding Debt  \
0        16938                 7                        4             35816   
1        17401                27                       12             26498   
2        23207                41                        9             43960   
3        57457                29                        3             34786   
4        88261                17                       10             13367   

    DTI  Credit_Worthy  
0  5.77              1  
1  3.01              1  
2  7.14              0  
3  5.66              1  
4  3.17              1

In [127]:
df["Credit_Worthy"].value_counts()

1    2845
0    2155
Name: Credit_Worthy, dtype: int64

In [128]:
# Splitting the dataset into X and y. 
X = df.drop(columns=["Credit_Worthy"])
y = df["Credit_Worthy"]


In [129]:
# Split the data using train_test_split
# Assigned a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

In [130]:
# Created a StandardScaler instance.
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

SVM Model

In [131]:
# Initiated SVC classifier model instance
svm_model = svm.SVC()

# Fit the model to the data using the training data
svm_model = svm_model.fit(X_train_scaled, y_train)
 
# Used the testing data to make the model predictions
svm_pred = svm_model.predict(X_test_scaled)



In [132]:
# Accuracy score 
accuracy_score(y_test, svm_pred)

0.9864

In [133]:
# Generated a confusion matrix for the model

confusion_matrix(y_test, svm_pred)

array([[525,   6],
       [ 11, 708]])

In [134]:
# Generated a classification report for the model
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       531
           1       0.99      0.98      0.99       719

    accuracy                           0.99      1250
   macro avg       0.99      0.99      0.99      1250
weighted avg       0.99      0.99      0.99      1250



GB Model

In [135]:
# Initialized Gradient Boosting Classifier
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Fit the model
gb_clf.fit(X_train_scaled, y_train)

# Predicted the labels
gb_pred = gb_clf.predict(X_test_scaled)

In [136]:
# Accuracy score 
accuracy_score(y_test, gb_pred)

1.0

In [137]:
# Generated a confusion matrix for the model

confusion_matrix(y_test, gb_pred)

array([[531,   0],
       [  0, 719]])

In [138]:
# Generated a classification report for the model
print(classification_report(y_test, gb_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       531
           1       1.00      1.00      1.00       719

    accuracy                           1.00      1250
   macro avg       1.00      1.00      1.00      1250
weighted avg       1.00      1.00      1.00      1250



Logistics Regression

In [139]:
# Initialized logistics Regression Classifier

lg_model = LogisticRegression(random_state=1)  

# Fit the model using training data
lg_model.fit(X_train_scaled,y_train)

LogisticRegression(random_state=1)

In [140]:
# Predicted the labels
lg_predictions = lg_model.predict(X_test_scaled)

In [141]:
# Accuracy score 
accuracy_score(y_test, lg_predictions)

0.9912

In [142]:
# Generated a confusion matrix for the model
confusion_matrix(y_test, lg_predictions)

array([[525,   6],
       [  5, 714]])

In [143]:
# Generated a classification report for the model

print(classification_report(y_test, lg_predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       531
           1       0.99      0.99      0.99       719

    accuracy                           0.99      1250
   macro avg       0.99      0.99      0.99      1250
weighted avg       0.99      0.99      0.99      1250



Random Forest

In [144]:

# Initialized random forest Classifier

rf_model = RandomForestClassifier(random_state=1)

# Fit the model using training data
rf_model.fit(X_train_scaled,y_train)

RandomForestClassifier(random_state=1)

In [145]:
# Predicted the labels

rf_predictions = rf_model.predict(X_test_scaled)

In [146]:
# Accuracy score 

accuracy_score(y_test, rf_predictions)

1.0

In [147]:

# Generated a confusion matrix for the model

confusion_matrix(y_test, rf_predictions)

array([[531,   0],
       [  0, 719]])

In [148]:
# Generated a classification report for the model

print(classification_report(y_test, rf_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       531
           1       1.00      1.00      1.00       719

    accuracy                           1.00      1250
   macro avg       1.00      1.00      1.00      1250
weighted avg       1.00      1.00      1.00      1250



Download Random Forest and Gradient Boosing Models


In [149]:
file_path = "random_forest_model.pkl"
joblib.dump(rf_model, file_path)

['random_forest_model.pkl']

In [150]:

file_path = "gb_model.pkl"
joblib.dump(gb_clf, file_path)

['gb_model.pkl']